name: Django CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Репони юклаш
      uses: actions/checkout@v3

    - name: Python ўрнатиш
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Зависимостларни ўрнатиш
      run: |
        pip install -r requirements.txt

    - name: Тестларни ишга тушириш
      run: |
        python manage.py test

    - name: EC2 серверга жойлаштириш
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd clothes-store
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
#name: Deploy Django Project to AWS EC2
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Подключение по SSH и деплой на EC2
#      uses: appleboy/ssh-action@v1.0.0
#      with:
#        host: ${{ secrets.EC2_HOST }}
#        username: ubuntu
#        key: ${{ secrets.EC2_SSH_KEY }}
#        script: |
#          cd /home/ubuntu/clothes-store
#          git pull origin main
#          source venv/bin/activate
#          pip install -r requirements.txt
#          python manage.py migrate
#          python manage.py collectstatic --noinput
#          sudo systemctl restart gunicorn